name: Atualizar Packagist

on:
  release:
    types: [published]  # Roda automaticamente quando um release for publicado
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar Packagist
        env:
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
        run: |
          curl -XPOST -H "Content-Type: application/json" \
          -d '{"repository":"https://github.com/Rafaelv-arc/crudphporm.git"}' \
          "https://packagist.org/api/update-package/?api_token=$PACKAGIST_TOKEN"
