name: Atualizar Packagist

on:
  release:
    types: [published]

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar Packagist
        run: |
          curl -X POST "https://packagist.org/api/update-package/?username=${{ secrets.PACKAGIST_USERNAME }}&api_token=${{ secrets.PACKAGIST_TOKEN }}" \
          -d '{"repository":"https://github.com/Rafaelv-arc/crudphporm"}' \
          -H "Content-Type: application/json"
